name: cook_cook
description: cook cook project
version: 1.0.0+1
authors:
  - Dan Crane <gre4kaDISCOUNT@gmail.com>

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^1.3.0

  # dev tools
  logger: ^1.0.0
  logging: ^1.0.1
  
  path_provider: ^2.0.2
  
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CeraPro
      fonts:
        - asset: assets/fonts/CeraPro/ttf/SeraPro-Regular.ttf
        # weight: 400
        # style: Regular
        - asset: assets/fonts/CeraPro/ttf/CeraPro-Medium.ttf
        # weight: 500
        # style: Medium
        - asset: assets/fonts/CeraPro/ttf/CeraPro-Bold.ttf
        # weight: 700
        # style: Bold
    - family: Kurale
      fonts:
        - asset: assets/fonts/Kurale/ttf/Kurale-Regular.ttf
